### ISSUE TITLE
Launcher for a shell script?

### ISSUE THREAD

**Issue by vnijs** [yuvipanda/jupyter-launcher-shortcuts#2]
Is it possible to setup a launcher for a shell script? It could run in the background, but even better would be in the terminal included with jupyterlab

**Comment by TidbitSoftware** [comment]
Did you ever resolve this using this extension?

**Comment by vnijs** [comment]
Not exactly, no. I ended up using jupyter's server proxy to open different apps. See example below. 

https://github.com/vnijs/jupyter-radiant-proxy

**Comment by TidbitSoftware** [comment]
Thanks for your response. I'm trying to create a Launcher entry that will run a bash script that simply copies assets from a shared directory to the user's home directory without launching a notebook or allowing web access. Are you aware of an existing extension that allows for this, or a straightforward was to add custom Launcher entries (without having to roll my own extension)? Sorry, but my Google Fu is failing me so far.

**Comment by vnijs** [comment]
Using the template I used for the extension might be a good place to start. You could try replacing the call to start R with some bash commands. If possible, I'd be interested to see what you come up with.

**Comment by TidbitSoftware** [comment]
Thanks again. It's increasingly looking like I will have to roll my own extension in order to achieve this and will share the results when done. Honestly, I'm surprised something like it doesn't exist already.

**Comment by TidbitSoftware** [comment]
I ended up using https://github.com/timkpaine/jupyterlab_commands to set up a number of Command Palette functions to call predefined scripts. The extension uses the server proxy as well, so it's effectively the same solution.
