### ISSUE TITLE
Compatibility with JupyterLab 1.x?

### ISSUE THREAD

**Issue by JamesSample** [yuvipanda/jupyter-launcher-shortcuts#4]
Hi @yuvipanda,

This extension looks great, but it's not compatible with recent versions of JupyterLab. Is something like this still the best way to link Launcher buttons to URLs, or are there alternative approaches that you'd recommend for JupyterLab >=1.1?

Thanks :-)

**Comment by BobCashStory** [comment]
need it too

**Comment by BobCashStory** [comment]
Can you do for 2.X also ?

**Comment by BobCashStory** [comment]
@yuvipanda  ? :/

**Comment by yuvipanda** [comment]
Unfortunately I don't have the cycles to do this right now :( would be great for someone else to send a pr?

**Comment by BobCashStory** [comment]
@yuvipanda looks someone did the work but not the Pr :
 [V2](https://github.com/sibylla-io/jupyter-launcher-shortcuts/tree/feature/jupyterlabv2.0)
So i did [PR](https://github.com/yuvipanda/jupyter-launcher-shortcuts/pull/6)

**Comment by BobCashStory** [comment]
Thanks @bsimpson53

**Comment by BobCashStory** [comment]
@yuvipanda can you release on pip and npm ?

**Comment by BobCashStory** [comment]
@yuvipanda  :/ ?

**Comment by BobCashStory** [comment]
@yuvipanda please release it !

**Comment by yuvipanda** [comment]
Apologies, @BobCashStory! I just published it, hope it works. I'm happy to add you to the npm authors list if you so wish.

**Comment by BobCashStory** [comment]
@yuvipanda thanks a lot ! yes you can add me !

**Comment by yuvipanda** [comment]
What is your npm username, @BobCashStory? I'll also give you merge rights to this repo :)

**Comment by BobCashStory** [comment]
@yuvipanda bobcashstory too  :) thanks a lot !

**Comment by yuvipanda** [comment]
@BobCashStory I've invited you! Can you confirm?

**Comment by BobCashStory** [comment]
@yuvipanda i'm in in npm ! not in guthub normal ?
